name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
    license:
        description: 'Unity manual license'
        required: false
        default: ''
runs:
    using: 'node12'
    main: 'dist/index.js'
