name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./

    - name: Create Activation File
      run: |
        Unity -nographics -createManualActivationFile -batchmode -logFile /dev/stdout
        Rename-Item -Path Unity_*.alf -NewName Unity.alf

    
    - name: Upload Activation File
      uses: actions/upload-artifact@v1
      with:
        name: Activation File
        path: 'Unity.alf'
        # upload this file to https://license.unity3d.com/manual
        # add the result as a secret called UNITY_LICENSE